# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\designer\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.configurationTab = QtWidgets.QWidget()
        self.configurationTab.setObjectName("configurationTab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.configurationTab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.configurationTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newButton = QtWidgets.QPushButton(self.groupBox)
        self.newButton.setObjectName("newButton")
        self.horizontalLayout.addWidget(self.newButton)
        self.openButton = QtWidgets.QPushButton(self.groupBox)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout.addWidget(self.openButton)
        self.saveButton = QtWidgets.QPushButton(self.groupBox)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.newClinicianButton = QtWidgets.QPushButton(self.groupBox)
        self.newClinicianButton.setObjectName("newClinicianButton")
        self.horizontalLayout.addWidget(self.newClinicianButton)
        self.editClinicianButton = QtWidgets.QPushButton(self.groupBox)
        self.editClinicianButton.setObjectName("editClinicianButton")
        self.horizontalLayout.addWidget(self.editClinicianButton)
        self.deleteClinicianButton = QtWidgets.QPushButton(self.groupBox)
        self.deleteClinicianButton.setObjectName("deleteClinicianButton")
        self.horizontalLayout.addWidget(self.deleteClinicianButton)
        self.verticalLayout.addWidget(self.groupBox)
        self.treeView = QtWidgets.QTreeView(self.configurationTab)
        self.treeView.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.treeView.setExpandsOnDoubleClick(True)
        self.treeView.setObjectName("treeView")
        self.verticalLayout.addWidget(self.treeView)
        self.tabWidget.addTab(self.configurationTab, "")
        self.schedulerTab = QtWidgets.QWidget()
        self.schedulerTab.setObjectName("schedulerTab")
        self.tabWidget.addTab(self.schedulerTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNew_Clinician = QtWidgets.QAction(MainWindow)
        self.actionNew_Clinician.setObjectName("actionNew_Clinician")
        self.actionEdit_Clinician = QtWidgets.QAction(MainWindow)
        self.actionEdit_Clinician.setObjectName("actionEdit_Clinician")
        self.actionDelete_Clinician = QtWidgets.QAction(MainWindow)
        self.actionDelete_Clinician.setObjectName("actionDelete_Clinician")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.newButton.clicked['bool'].connect(self.actionNew.trigger)
        self.openButton.clicked['bool'].connect(self.actionOpen.trigger)
        self.saveButton.clicked['bool'].connect(self.actionSave.trigger)
        self.newClinicianButton.clicked['bool'].connect(self.actionNew_Clinician.trigger)
        self.editClinicianButton.clicked['bool'].connect(self.actionEdit_Clinician.trigger)
        self.deleteClinicianButton.clicked['bool'].connect(self.actionDelete_Clinician.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.newButton.setText(_translate("MainWindow", "New"))
        self.openButton.setText(_translate("MainWindow", "Open"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.newClinicianButton.setText(_translate("MainWindow", "New Clinician"))
        self.editClinicianButton.setText(_translate("MainWindow", "Edit Clinician"))
        self.deleteClinicianButton.setText(_translate("MainWindow", "Delete Clinician"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.configurationTab), _translate("MainWindow", "Configuration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.schedulerTab), _translate("MainWindow", "Scheduler"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open configuration file..."))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setToolTip(_translate("MainWindow", "Create new configuration file..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Save changes to configuration file..."))
        self.actionNew_Clinician.setText(_translate("MainWindow", "New Clinician"))
        self.actionNew_Clinician.setToolTip(_translate("MainWindow", "Add a new clinician to the configuration file..."))
        self.actionEdit_Clinician.setText(_translate("MainWindow", "Edit Clinician"))
        self.actionEdit_Clinician.setToolTip(_translate("MainWindow", "Edit the selected clinician"))
        self.actionDelete_Clinician.setText(_translate("MainWindow", "Delete Clinician"))
        self.actionDelete_Clinician.setToolTip(_translate("MainWindow", "Delete the selected clinician"))

